In [2]:
import sys

!{sys.executable} --version

Python 3.11.7


https://github.com/DeepReinforcementLearning/DeepReinforcementLearningInAction

## Sampling 

In [3]:
from collections import deque
replay = deque(maxlen=10)
for i in range(20):
    replay.append(i)
replay

deque([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], maxlen=10)

In [4]:
import random
random.sample(replay, 5)

[11, 13, 18, 14, 16]

## Index

In [5]:
replay = deque(maxlen=10)
for i in range(20):
    replay.append((i, i+1, i+2))
replay

deque([(10, 11, 12),
       (11, 12, 13),
       (12, 13, 14),
       (13, 14, 15),
       (14, 15, 16),
       (15, 16, 17),
       (16, 17, 18),
       (17, 18, 19),
       (18, 19, 20),
       (19, 20, 21)],
      maxlen=10)

In [6]:
sample = random.sample(replay, 5)
sample

[(15, 16, 17), (16, 17, 18), (14, 15, 16), (13, 14, 15), (11, 12, 13)]

In [10]:
import numpy as np
np.array(sample)[:, [0]]

array([[15],
       [16],
       [14],
       [13],
       [11]])

## Torch

In [28]:
import torch
a = torch.Tensor([[1,2,3]])
b = torch.Tensor([[4,5,6]])
torch.cat((a, b), 0)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
torch.cat((a, b), 1)

tensor([[1., 2., 3., 4., 5., 6.]])